[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  path = "/urun/*"
  function = "seo-bot"

[[edge_functions]]
  path = "/magaza/*"
  function = "seo-bot"

# --- OTOMATİK SİTEMAP ROBOTU (Çoklu Alt Sayfa Desteği) ---
[[edge_functions]]
  path = "/sitemap.xml"
  function = "sitemap"

[[edge_functions]]
  path = "/sitemap-products-*.xml"
  function = "sitemap-products"
