[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  path = "/urun/*"
  function = "seo-bot"

[[edge_functions]]
  path = "/magaza/*"
  function = "seo-bot"

# --- YENİ EKLENEN OTOMATİK SİTEMAP ROBOTU ---
[[edge_functions]]
  path = "/sitemap.xml"
  function = "sitemap"
